### ISSUE TITLE
RTT on WB-FC-Firmware

### ISSUE THREAD

**Issue by davinbirdi** [UBC-Rocket/Whistler-Blackcomb-v2#50]
Next time I'm on that board I will add this so that we can use RTT to debug at faster speeds than printfs.

I've set up the first commit on the DAQ firmware so it works nicely to transfer over.

**Comment by Esouder** [comment]
As of [0ac6c7c](https://github.com/UBC-Rocket/Whistler-Blackcomb-v2/commit/0ac6c7ce2630989719948458276969c4a5356cf7), RTT builds on MCUXpresso for WB-FC. Still need to test if it works and make sure that it hasn't broken x86 compilation.

**Comment by Esouder** [comment]
I think it would be a good idea to do something will build flags so we can control whether this (and maybe other 'debug' code) is included in builds. We don't need this on the actual flight, so it would be good to be able to add and remove this functionality without having to make large changes to the codebase.

**Comment by Esouder** [comment]
I can confirm that RTT is working on the flight computer. There were some issues where it didn't seem to be working, but that's just because the IMU task was fucked up and killing everything somehow.

![image](https://user-images.githubusercontent.com/37464714/193978963-9cd304c6-2994-44d0-a639-e4695ae226d2.png)

With the IMU task removed, RTT works (at least for sending messages, which is all I need it for at the moment, so should be able to package this up cleanly pretty quick and merge it in.

I also made a very minor update the RTT documentation about where it's located on windows.

**Comment by Esouder** [comment]
Moved it into the HAL to make things nicer for x86. Will test again, should be good to go after that. 

Am I jinxing myself? of course. Do I care? Of course not. Will I suffer for my hubris? Absolutely.

**Comment by Esouder** [comment]
Tested it, still works fine.
